### ISSUE TITLE
FAQ?

### ISSUE THREAD

**Issue by rubyFeedback** [SH20RAJ/Sopplayer#1]
Hey there SH20RAJ,

Could you consider adding a short FAQ that explains a few things?

For instance, why do we have to use class sopplayer? Why do we have
to use data-setup = "{}"?

I would love to read up on this if possible.

Also I have tried soppplayer, it works, but I would like to shrink the
default thumbnail picture or so to 150px; it seems to display the real
width and height. How can we shrink it? Could this info be added,
either to main README or a FAQ?

At any rate thank you for reading.

**Comment by rubyFeedback** [comment]
Also how can we customize the default looks? I need a variant for dark background.

Edit: Nevermind, I just noticed width: 500px shown in the code.

**Comment by SH20RAJ** [comment]
SopPlayer is made by customising videojs, Try customising the css file (only)
